[CmdletBinding()]
param(
    [switch]$NoPull
)

$ErrorActionPreference = "Stop"

function Get-GitText {
    param(
        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]]$GitArgs
    )

    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = & git @GitArgs 2>$null
        if ($LASTEXITCODE -ne 0) {
            return ""
        }
    }
    finally {
        $ErrorActionPreference = $previousPreference
    }

    return (($output | ForEach-Object { $_.ToString() }) -join "`n").Trim()
}

function Get-CommandText {
    param(
        [string]$Command,
        [string[]]$Arguments
    )

    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = & $Command @Arguments 2>$null
        if ($LASTEXITCODE -ne 0) {
            return ""
        }
    }
    finally {
        $ErrorActionPreference = $previousPreference
    }

    return (($output | ForEach-Object { $_.ToString() }) -join "`n").Trim()
}

function Format-Block {
    param([string]$Text)

    if ([string]::IsNullOrWhiteSpace($Text)) {
        return "_None._"
    }

    return "``````text`n$Text`n``````"
}

$repoRoot = Get-GitText rev-parse --show-toplevel
if ([string]::IsNullOrWhiteSpace($repoRoot)) {
    throw "This script must be run from inside a Git repository."
}

Set-Location $repoRoot

$contextDir = Join-Path $repoRoot ".agent-context"
$contextPath = Join-Path $contextDir "latest.md"
New-Item -ItemType Directory -Force -Path $contextDir | Out-Null

$remoteUrl = Get-GitText remote get-url origin
if (-not [string]::IsNullOrWhiteSpace($remoteUrl)) {
    & git fetch origin --prune | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to fetch origin."
    }
}

$branch = Get-GitText branch --show-current
if ([string]::IsNullOrWhiteSpace($branch)) {
    $branch = "HEAD"
}

$upstream = Get-GitText rev-parse --abbrev-ref --symbolic-full-name "@{u}"
$syncNote = "No upstream branch is configured."

if (-not [string]::IsNullOrWhiteSpace($upstream)) {
    $statusBeforePull = Get-GitText status --porcelain
    $hasWorktreeChanges = -not [string]::IsNullOrWhiteSpace($statusBeforePull)

    if ($NoPull) {
        $syncNote = "Fetch completed. Pull skipped because -NoPull was supplied."
    }
    elseif ($hasWorktreeChanges) {
        $syncNote = "Fetch completed. Pull skipped because the worktree has local changes."
    }
    else {
        $aheadBehind = Get-GitText rev-list --left-right --count "$branch...$upstream"
        if (-not [string]::IsNullOrWhiteSpace($aheadBehind)) {
            $parts = $aheadBehind -split "\s+"
            $localAhead = [int]$parts[0]
            $remoteAhead = [int]$parts[1]

            if ($remoteAhead -gt 0 -and $localAhead -eq 0) {
                & git pull --ff-only | Out-Null
                if ($LASTEXITCODE -ne 0) {
                    throw "Fast-forward pull failed."
                }
                $syncNote = "Fetched origin and fast-forwarded $branch from $upstream."
            }
            elseif ($remoteAhead -gt 0 -and $localAhead -gt 0) {
                $syncNote = "Fetched origin. Local and upstream histories have diverged; manual review is required."
            }
            elseif ($localAhead -gt 0) {
                $syncNote = "Fetched origin. Local branch is ahead of $upstream."
            }
            else {
                $syncNote = "Fetched origin. Local branch is up to date with $upstream."
            }
        }
    }
}

$defaultBranch = ""
if (-not [string]::IsNullOrWhiteSpace($remoteUrl) -and (Get-Command gh -ErrorAction SilentlyContinue)) {
    $defaultBranch = Get-CommandText gh @("repo", "view", "--json", "defaultBranchRef", "--jq", ".defaultBranchRef.name")
}

if ([string]::IsNullOrWhiteSpace($defaultBranch)) {
    $defaultBranch = $branch
}

$status = Get-GitText status --short --branch
$statusLines = @()
if (-not [string]::IsNullOrWhiteSpace($status)) {
    $statusLines = $status -split "`n" | Where-Object { $_ -notmatch "^\?\? \.agent-context/" -and $_ -notmatch "^ M \.agent-context/" }
}
$statusText = ($statusLines -join "`n").Trim()

$logRef = $upstream
if ([string]::IsNullOrWhiteSpace($logRef)) {
    $logRef = "HEAD"
}

$recentCommits = Get-GitText log --oneline --decorate -n 8 $logRef
$openIssues = ""
$openPrs = ""

if (-not [string]::IsNullOrWhiteSpace($remoteUrl) -and (Get-Command gh -ErrorAction SilentlyContinue)) {
    $openIssues = Get-CommandText gh @("issue", "list", "--limit", "8", "--state", "open")
    $openPrs = Get-CommandText gh @("pr", "list", "--limit", "8", "--state", "open")
}

$updatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")

$content = @"
# Latest Local Agent Context

Generated by ``scripts/update-context.ps1``.

## Sync

- Updated at: $updatedAt
- Repository root: ``$repoRoot``
- Origin: ``$remoteUrl``
- Branch: ``$branch``
- Upstream: ``$upstream``
- Default branch: ``$defaultBranch``
- Sync note: $syncNote

## Git Status

$(Format-Block $statusText)

## Recent Commits

$(Format-Block $recentCommits)

## Open Issues

$(Format-Block $openIssues)

## Open Pull Requests

$(Format-Block $openPrs)

## Agent Checklist

1. Treat GitHub as the source of truth for task context.
2. Read ``AGENTS.md`` and ``docs/context.md`` before editing.
3. Preserve user changes and avoid destructive Git operations.
4. Capture durable follow-ups as GitHub issues or experiment notes.
"@

$existing = ""
if (Test-Path $contextPath) {
    $existing = Get-Content -Raw $contextPath
}

if ($existing -ne $content) {
    Set-Content -Path $contextPath -Value $content -Encoding UTF8
}

Write-Host "Updated $contextPath"
Write-Host $syncNote
